package simulaed;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import estruturas.PilhaSeq;

/**
 *
 * @author rayss
 */
public final class JanelaPilhaSeq extends javax.swing.JDialog {
    
    PilhaSeq pilha;
    ArrayList<Bloco> blocos;
    int tamPilha;    
    int top;
    
    Border bordaVerde    = BorderFactory.createLineBorder(Color.GREEN, 2);
    Border bordaVermelha = BorderFactory.createLineBorder(Color.RED, 2);
    Border bordaAmarela  = BorderFactory.createLineBorder(Color.YELLOW, 2);
    Border bordaVazia    = BorderFactory.createEmptyBorder();
    Border bordaPreta    = BorderFactory.createLineBorder(Color.GRAY, 2);
    
    boolean cor;
    final int DELAY = 2000;

    /**
     * Creates new form JanelaPilhaSeq
     */
    public JanelaPilhaSeq(java.awt.Frame parent, boolean modal, int tamanho) {
        super(parent, modal);
        initComponents();
        configBtn();
        
        pilha = new PilhaSeq(tamanho);
        blocos = new ArrayList<>(tamanho);
        
        setTitle("Pilha (Sequencial)");
        setLocationRelativeTo(null);
        
        top = 0;
        int x  = canvas.getSize().width;
        int y  = canvas.getSize().height;
        x/=2;
        x -= 35;
        y -= 73;       
                
        // Desenha a lista Inicial na tela
        for (int i = 0; i < tamanho; i++) {
            Bloco b = new Bloco();
            b.setValor(0);           
            b.setLocation(x, y - (b.getSize().height + 5)*i );
            canvas.add(b);  
            blocos.add(b);
            //b.setVisible(false);
            b.setContentAreaFilled(false);
            b.setBorder(bordaPreta);
            b.setEnabled(false);
        }
    }
    
    private void configBtn(){
        btnInserir.setMnemonic(KeyEvent.VK_I);
        btnInserir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                String s = txtValor.getText();
                if(s.equals(""))
                    return;
                int v = Integer.parseInt(s);
                try{
                    boolean ok = pilha.push(v);

                    if (ok) {
                       Bloco b;
                       b = blocos.get(top);
                       b.setValor(v);
                       //lblTopo.setText(""+pilha.tamanho());
                       lblTopo.setText(""+pilha.top());
                       lblElementos.setText(""+pilha.tamanho());
                       top++;

                       //Mudar as cores
                       b.setBorder(bordaAmarela);
                       b.setContentAreaFilled(true);
                       b.setEnabled(true);
                       if(top > 1){
                           Bloco ant = blocos.get(top-2);
                           ant.setBorder(bordaVazia);
                       }

                   }
               }catch(Exception e){
                   JOptionPane.showMessageDialog(rootPane, e.getMessage());                
               }                
                
            }
        });        
        
        btnRemover.setMnemonic(KeyEvent.VK_R);
        btnRemover.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
           
               try{                   
                   pilha.pop();
                   top--;
                   //lblTopo.setText(""+pilha.tamanho());
                   if(pilha.tamanho()!=0)
                       lblTopo.setText(""+pilha.top());                       
                   else
                       lblTopo.setText("---");
                   lblElementos.setText(""+pilha.tamanho());
                   
                   //Mudar as cores
                   if(top > 0){
                    Bloco b = blocos.get(top-1);
                    b.setBorder(bordaAmarela);
                   }
                   Bloco post = blocos.get(top);
                   //post.setBorder(bordaVazia);
                   post.setBorder(bordaPreta);
                   post.setContentAreaFilled(false);
                   post.setEnabled(false);
                   
               }catch(Exception e){
                   JOptionPane.showMessageDialog(rootPane, e.getMessage());
               }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserir = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblValor1 = new javax.swing.JLabel();
        lblTopo = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblElementos = new javax.swing.JLabel();
        canvas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnInserir.setText("Inserir");

        btnRemover.setText("Remover");

        lblValor.setText("Valor:");

        lblValor1.setText("Topo:");

        lblTopo.setFont(new java.awt.Font("Arimo", 0, 36)); // NOI18N
        lblTopo.setText("---");

        lblValor2.setText("N Elementos:");

        lblElementos.setFont(new java.awt.Font("Arimo", 0, 36)); // NOI18N
        lblElementos.setText("---");

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopo)
                    .addComponent(lblElementos))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserir)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor))
                        .addGap(28, 28, 28)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTopo)
                            .addComponent(lblValor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblElementos)
                            .addComponent(lblValor2))))
                .addContainerGap(502, Short.MAX_VALUE))
            .addComponent(canvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel canvas;
    private javax.swing.JLabel lblElementos;
    private javax.swing.JLabel lblTopo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
